Add lesson topic info/guidance
carpentries/curriculum-development pull request #56
Opened 2020-09-07 16:31 UTC by tobyhodges

Introducing some information about lesson repository topics for Incubator repos, and linking to the sheet of all topics currently in use across the Incubator.

Not sure if this is the best place to be adding this information, so please advise if you think it's a better fit somewhere else.

2020-09-08 23:09 UTC, ErinBecker commented on 07-lesson-life-cycle.Rmd
> +develops new curriculum together.
curriculum --> curricula

2020-09-08 23:10 UTC, ErinBecker commented on 07-lesson-life-cycle.Rmd
> +New lessons are suggested for development and added to Incubator via the [Proposals][proposals] repository,
"the Incubator"

2020-09-08 23:11 UTC, ErinBecker commented on 07-lesson-life-cycle.Rmd
> +based on topics added to the lesson repository.
topics --> "topic tags"?

2020-09-08 23:13 UTC, ErinBecker commented on 07-lesson-life-cycle.Rmd
> +based on topics added to the lesson repository.
I know these metadata elements are referred to by GitHub just as "topics", but I think that usage is a bit outside of normal vernacular English usage and can be confusing. I'm proposing that we refer to GitHub "topics" as "topic tags" and/or explicitly state somewhere that these are metadata elements and link to GitHub documentation about "topics".

2020-09-08 23:13 UTC, ErinBecker commented on 07-lesson-life-cycle.Rmd
> +Some topics are essential, while others are more flexible.
topics --> "topic tags"

2020-09-08 23:14 UTC, ErinBecker commented on 07-lesson-life-cycle.Rmd
> +See the table below for guidance about the types and number of topics each
topics --> "topic tags"

2020-09-08 23:16 UTC, ErinBecker commented on 07-lesson-life-cycle.Rmd
> +*Categories marked with an asterisk (\*) are essential.*
essential --> "required in order for your lesson to appear and be appropriately sorted on the Community Developed Lessons page."

2020-09-08 23:17 UTC, ErinBecker commented on 07-lesson-life-cycle.Rmd
> +The Curriculum Team will support you in setting topics for your lesson.
setting topics --> "setting appropriate topic tags"

2020-09-08 23:19 UTC, ErinBecker commented on 07-lesson-life-cycle.Rmd
> +To help ensure consistency across our lesson repositories,
"our lesson repositories" - @tobyhodges could you please do a sweep through this file (and other places where you are updating documentation) to make sure we're not using "our" or "The Carpentries" when referring to lessons in the Incubator? Here, for example, we could say "to help ensure consistency across all lesson repositories developed by The Carpentries community".

2020-09-08 23:20 UTC, ErinBecker commented on 07-lesson-life-cycle.Rmd
> +creating new topics where no pre-existing label exists for your lesson.
"creating new topic tags"

2020-09-08 23:20 UTC, ErinBecker commented on 07-lesson-life-cycle.Rmd
> +creating new topics where no pre-existing label exists for your lesson.
Do we want people to add things directly to the spreadsheet?

2020-09-08 23:21 UTC, ErinBecker requested changes
@tobyhodges - looking good with a few suggested minor changes around language. Please take a look at my comments and see what you think.

2020-09-09 07:54 UTC, tobyhodges commented
I had been using "topic tags" in my first draft but switched to "topics" when I considered that Git & GitHub already use the term "tags" to mean something else. In particular, GitHub uses it for releases and I worried that this might case more confusion. We face a similar problem with "topic labels," since labels are used on issues...

I do agree that "topic tags" reads better, though: it's clearer that we're talking about applying metadata to the lesson, rather than influencing the actual content. I'll make the changes and we can revisit if I or anyone else can think of a more distinct/appropriate term.

2020-09-09 09:55 UTC, tobyhodges commented on 07-lesson-life-cycle.Rmd
> +creating new topics where no pre-existing label exists for your lesson.
It's currently set to allow anyone visiting to comment on the sheets. I'd prefer to maintain the document myself. 

In the long run I'm hoping the Infrastructure team can help me with keeping the list up-to-date, but for now I'll be updating it via regular sweeps of the lesson repositories.

2020-09-09 10:00 UTC, tobyhodges commented
Now I've finished updating, it has occurred to me that this material might be better placed in a different location. Information about working with and in The Carpentries Incubator might be more appropriate in the Technological Introductions section (or a new section on its own)? A description of adding topic tags doesn't feel like part of the discussion of lesson life cycle, adn we'll almost certainly end up adding more material about the Incubator (e.g. details of curriculum community activities, etc). What do you think, @ErinBecker?

2020-09-10 10:19 UTC, tobyhodges commented
Based on offline discussion with @ErinBecker I'm going to move this to begin a new appendix, which will contain documentation for the Carpentries Incubator. Closing this PR now. I'll open a new one with the content in a different location.

2020-09-10 10:19 UTC, closed without merging